
# ======================================================
# Application
# ======================================================
spring.application.name=api-gateway

# ======================================================
# Server
# ======================================================
server.port=8080

# ======================================================
# Gateway Routes
# ======================================================

spring.cloud.gateway.server.webmvc.routes[0].id=employee-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/employees/**

# ======================================================
# Actuator
# ======================================================

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always

# ======================================================
# Logging
# ======================================================

logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.web=INFO
logging.level.com.eems=DEBUG